/*-----------------------------------------------------------------------------
    Name: 07_Tx_Welcome
    Generated By: cavisson
    Date of generation: 07/05/2021 04:14:34
    Flow details:
    Build details: 4.6.1 (build# 34)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void 07_Tx_Welcome()
{
    ns_start_transaction ("07_Tx_Welcome");
    ns_web_url ("welcome",
        "URL=http://184.105.48.40/cgi-bin/welcome",
        "METHOD=GET"
    );
    ns_end_transaction ("07_Tx_Welcome", NS_AUTO_STATUS);
    ns_page_think_time(3.0);


}