/*-----------------------------------------------------------------------------
    Name: exit_script
    Generated By: cavisson
    Date of generation: 07/05/2021 04:14:34
    Flow details:
    Build details: 4.6.1 (build# 34)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int exit_script()
{
    return 0;
}
